wip

diff --git a/.github/workflows/preview-comment.yml b/.github/workflows/preview-comment.yml
--- a/.github/workflows/preview-comment.yml
+++ b/.github/workflows/preview-comment.yml
@@ -7,49 +7,102 @@ on:
     types:
       - requested
 
+concurrency: preview-comment
+
 jobs:
   preview-comment:
     runs-on: ubuntu-latest
     steps:
-      - name: 'Download artifact'
-        uses: actions/github-script@v6
-        with:
-          script: |
-            let matchArtifact = undefined
-            while (true) {
-              console.log("do listWorkflowRunArtifacts")
-              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
-                 owner: context.repo.owner,
-                 repo: context.repo.repo,
-                 run_id: context.payload.workflow_run.id,
-              });
-              matchArtifact = allArtifacts.data.artifacts.find((artifact) => {
-                return artifact.name == "ipfs-id"
-              });
-              if (matchArtifact) {
-                console.log("found artifact " + matchArtifact.id)
-                break
-              }
-              console.log("artifact not found, retrying")
-              await new Promise(r => setTimeout(r, 5000));
-            }
-            let download = await github.rest.actions.downloadArtifact({
-               owner: context.repo.owner,
-               repo: context.repo.repo,
-               artifact_id: matchArtifact.id,
-               archive_format: 'zip',
-            });
-            let fs = require('fs');
-            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/ipfs-id.zip`, Buffer.from(download.data));
-      - name: 'Unzip artifact'
-        run: unzip ipfs-id.zip
-      - run: |
-          cat ipfs_id
-          cat pr_number
+      - name: Install some tools
+        run: |
+          apt update
+          apt install -y nmap # for ncat
+          wget https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz
+          tar xzf age-v1.1.1-linux-amd64.tar.gz
+          mv age/age* /usr/bin/
+      - name: Install ipfs
+        run: |
+          wget -q https://dist.ipfs.tech/kubo/v0.20.0/kubo_v0.20.0_linux-amd64.tar.gz
+          tar -xvzf kubo_v0.20.0_linux-amd64.tar.gz
+          ./kubo/install.sh
+      - name: ipfs init
+        run: |
+          ipfs init
+          ipfs config --json Experimental.Libp2pStreamMounting true
+          ipfs daemon &
+          sleep 5
+      - name: Import ipfs key
+        run: |
+          echo $KLUCTL_PREVIEW_IPNS_KEY > kluctl-preview-comment.pem
+          ipfs key import kluctl-preview-comment kluctl-preview-comment.pem -f pem-pkcs8-cleartext
+      - name: Publish own ID
+        run: |
+          cat <<EOF > ipns.json
+          {
+            "workflow_run_id": "${{ context.payload.workflow_run.id }}",
+            "ipfs_id": "$(ipfs id -f "<id>")"
+          }
+          EOF
+          h=$(ipfs add ipns.json -q)
+          echo h=$h
+          ipfs name publish --key kluctl-preview-comment --ttl 30s /ipfs/$h
+      - name: Wait for info
+        id: info
+        run: |
+          echo $KLUCTL_PREVIEW_AGE_KEY > age.key
+          ipfs p2p listen /x/kluctl-preview-info /ip4/127.0.0.1/tcp/10001
+          while true; do
+            echo "waiting for info..."
+            if ! ncat -l 127.0.0.1 10001 > info.json.age; then
+              echo "receiving failed...retrying..."
+              sleep 5
+              continue
+            do
+
+            if ! age -d -i age.key -o info.json info.json.age; then
+              echo "decryption failed...retrying..."
+              sleep 5
+              continue
+            fi
+
+            RUN_ID=$(cat info.json | jq '.workflow_run_id' -r)
+            if [ "$RUN_ID" != "${{ context.payload.workflow_run.id }}" ]; then
+              echo "RUN_ID=$RUN_ID"
+              echo "unexpected run id...retrying..."
+              sleep 5
+              continue
+            fi
+
+            export GITHUB_TOKEN=$(cat info.json | jq '.github_token' -r)
+            gh api -XPOST -F 'query=query UserCurrent{viewer{login}}' /graphql > user.json
+            if [ "$(cat user.json | jq '.data.viewer.login' -r)" != "github-actions[bot]" ]; then
+              echo "unexpected github token...retrying..."
+              sleep 5
+              continue
+            fi
+
+            gh api /installation/repositories > repos.json
+            if [ "$(cat repos.json | jq '.total_count' -r)" != "1" -o "$(cat repos.json | jq '.repositories[0].full_name' -r)" != "${{ github.repository }}" ]; then
+              cat repos.json
+              echo "unexpected github token repositories...retrying..."
+              sleep 5
+              continue
+            fi
+
+            echo "token seems to be fine!"
+            break
+          done
+
+          cat info.json | jq ".ipfs_id" -r > ipfs_id
+          cat info.json | jq ".pr_number" -r > pr_number
+
+          echo "ipfs_id=$(cat ipfs_id)"
+          echo "pr_number=$(cat pr_number)"
+
+          echo "ipfs_id=$(cat ipfs_id)" >> $GITHUB_OUTPUT
+          echo "pr_number=$(cat pr_number)" >> $GITHUB_OUTPUT
       - name: Build comment text
         run: |
-          ipfs_id=$(cat ipfs_id)
-
           cat <<EOF > comment.md
           # 🤖 Preview Environment
           The preview environment is starting up.
@@ -59,13 +112,9 @@ jobs:
           ssh: \`ipfs p2p forward /x/ssh /ip4/127.0.0.1/tcp/9090 /p2p/$(cat ipfs_id)\`
           k8s: \`ipfs p2p forward /x/k /ip4/127.0.0.1/tcp/9090 /p2p/$(cat ipfs_id)\`
           EOF
-      - id: pr
-        run: |
-          echo "pr_number=$(cat pr_number)" >> $GITHUB_OUTPUT
-      - run: echo pr_number=${{ steps.pr.outputs.pr_number }}
       - uses: mshick/add-pr-comment@v2
         with:
-          issue: ${{ steps.pr.outputs.pr_number }}
+          issue: ${{ steps.info.outputs.pr_number }}
           message-id: preview-run-info
           message-path: |
             comment.md
diff --git a/.github/workflows/preview-run.yml b/.github/workflows/preview-run.yml
--- a/.github/workflows/preview-run.yml
+++ b/.github/workflows/preview-run.yml
@@ -15,62 +15,18 @@ permissions:
   pull-requests: write
 
 jobs:
-  ipfs-init:
-    # only run on preview-branches and on PRs with the preview label
-    if: ${{ github.event.label.name == 'preview' || contains(github.event.pull_request.labels.*.name, 'preview') }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: test
-        run: |
-          echo ${{ secrets.GITHUB_TOKEN }} | base64
-      - name: test2
-        run: |
-          echo asd
-          sleep 10000
-      - name: Install ipfs
-        run: |
-          wget -q https://dist.ipfs.tech/kubo/v0.20.0/kubo_v0.20.0_linux-amd64.tar.gz
-          tar -xvzf kubo_v0.20.0_linux-amd64.tar.gz
-          ./kubo/install.sh
-      - name: ipfs init
-        run: |
-          ipfs init
-          ipfs config --json Experimental.Libp2pStreamMounting true
-      - name: compress and encrypt ipfs folder
-        run: |
-          tar czf ipfs.tar.gz ~/.ipfs
-          gpg --batch --passphrase $(echo $GITHUB_TOKEN | base64) -c ipfs.tar.gz
-      - name: gather additional info
-        run: |
-          ipfs id -f "<id>" > ./ipfs_id
-          echo "${{ github.event.number }}" > ./pr_number
-          cat pr_number
-      - uses: actions/upload-artifact@v3
-        with:
-          name: ipfs-config
-          path: ipfs.tar.gz.gpg
-      - uses: actions/upload-artifact@v3
-        with:
-          name: ipfs-id
-          path: |
-            ipfs_id
-            pr_number
-
   preview-run:
     if: ${{ github.event.label.name == 'preview' || contains(github.event.pull_request.labels.*.name, 'preview') }}
     runs-on: ubuntu-latest
     needs: ipfs-init
     steps:
-      # DOWNLOAD IPFS CONFIG
-      - name: Download ipfs-config
-        uses: actions/download-artifact@v3
-        with:
-          name: ipfs-config
-      - name: Decrypt and extract ipfs-config
+      - name: Install some tools
         run: |
-          gpg --batch --passphrase $(echo $GITHUB_TOKEN | base64) -d ipfs.tar.gz.gpg > ipfs.tar.gz
-          tar xzf ipfs.tar.gz
-          mv home/runner/.ipfs ~/
+          apt update
+          apt install -y nmap # for ncat
+          wget https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz
+          tar xzf age-v1.1.1-linux-amd64.tar.gz
+          mv age/age* /usr/bin/
       # SETUP IPFS
       - name: Install ipfs
         run: |
@@ -79,7 +35,9 @@ jobs:
           ./kubo/install.sh
       - name: Setup ipfs
         run: |
-          ipfs daemon &
+          ipfs init
+          ipfs config --json Experimental.Libp2pStreamMounting true
+          ipfs daemon --enable-pubsub-experiment &
           sleep 5
       - name: Setup ssh
         run: |
@@ -88,6 +46,47 @@ jobs:
           sudo systemctl enable ssh
           sudo systemctl start ssh
           ipfs p2p listen /x/ssh /ip4/127.0.0.1/tcp/22
+      # QUERY IPNS
+      - name: Query IPNS
+        id: ipns
+        run: |
+          while true; do
+            echo "waiting for IPNS..."
+            ipfs cat /ipns/k51qzi5uqu5diql7mejg4dfn35igqqf22202vgv3sepjrsobtya2xihqqtshbe > ipns.json
+            echo "ipns.json="
+            cat ipns.json
+            run_id=$(cat ipns.json | jq '.workflow_run_id' -r)
+            if [ "$run_id" != "${{ github.run_id }}" ]; then
+              echo "IPNS seems to be out-of-date...retrying...
+              sleep 5
+              continue
+            fi
+            echo "comment_ipfs_id=$(cat ipns.json | jq '.ipfs_id' -r)" >> $GITHUB_OUTPUT
+            break
+          done
+      # SEND INFO
+      - name: send info
+        run: |
+          cat <<EOF > info.json
+          {
+            "workflow_run_id": "${{ github.run_id }}",
+            "github_token": "${{ secrets.GITHUB_TOKEN }}",
+            "ipfs_id": "$(ipfs id -f "<id>")",
+            "pr_number": "${{ github.event.number }}"
+          }
+          EOF
+          age -r -r age1mypja0mcvg04090amd79zv07atquflnazl0x0uyt7ugqq94ev5yqjxjq50 info.json -o info.json.age
+
+          ipfs p2p forward /x/kluctl-preview-info /ip4/127.0.0.1/tcp/10001 /p2p/${{ steps.ipns.outputs.comment_ipfs_id }}
+          while true; do
+            echo "sending info.json..."
+            if ! cat info.json.age | ncat 127.0.0.1 10001; then
+              echo "failed to send info.json...retrying...
+              sleep 5
+              continue
+            fi
+            break
+          done
       # SETUP KIND
       - name: Setup Kind cluster
         run: |
