wip

diff --git a/.github/workflows/preview-run.yml b/.github/workflows/preview-run.yml
--- a/.github/workflows/preview-run.yml
+++ b/.github/workflows/preview-run.yml
@@ -15,13 +15,6 @@ jobs:
     if: ${{ github.event.label.name == 'preview' || contains(github.event.pull_request.labels.*.name, 'preview') }}
     runs-on: ubuntu-latest
     steps:
-      - name: test
-        run: |
-          echo ${{ secrets.GITHUB_TOKEN }} | base64
-      - name: test2
-        run: |
-          echo test2
-          sleep 100000
       - name: Set up Go
         uses: actions/setup-go@v4
         with:
@@ -153,12 +146,24 @@ jobs:
       - name: send info
         run: |
           static_ipns_name=$(ipfs key gen static-webui)
-          while ! ./hack/ipfs-exchange-info/ipfs-exchange-info -mode send-info -workflow-run-id ${{ github.run_id }} \
-            --age-pub-key age1dhueesr5qj8e8uy298k7z8x3ntv620rde89phumg0kvjx2t32elsm759z7 \
-            --ipfs-id $(cat ipfs_id) --static-ipns-name $static_ipns_name; do
-            sleep 1
+          while true; do
+            if ! ./hack/ipfs-exchange-info/ipfs-exchange-info -mode resolve-ipns -pr-number ${{ github.event.pull_request.number }} -ipns-name k51qzi5uqu5diql7mejg4dfn35igqqf22202vgv3sepjrsobtya2xihqqtshbe > ipfs_id; then
+              echo "Resolving IPNS failed...retrying..."
+              sleep 1
+              continue
+            fi
+            echo "ipfs_id=$(cat ipfs_id)"
+            if ! ./hack/ipfs-exchange-info/ipfs-exchange-info -mode send-info -pr-number ${{ github.event.pull_request.number }} -age-pub-key age1dhueesr5qj8e8uy298k7z8x3ntv620rde89phumg0kvjx2t32elsm759z7 --ipfs-id $(cat ipfs_id) --static-ipns-name $static_ipns_name; then
+              echo "Resolving info failed...retrying..."
+              sleep 1
+              continue
+            fi
+            break
           done
         env:
+          # we send the GITHUB_TOKEN to the preview-comment workflow. This token is then verified to be from a workflow
+          # that runs inside this repo, which can only be a workflow that got manually approved. The token is encrypted
+          # via age
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       # GENERATE STATIC WEBUI
       - name: Publish static webui and sleep
