wip

diff --git a/.github/workflows/preview-run.yml b/.github/workflows/preview-run.yml
--- a/.github/workflows/preview-run.yml
+++ b/.github/workflows/preview-run.yml
@@ -43,7 +43,13 @@ jobs:
         run: |
           while true; do
             echo "waiting for IPNS..."
-            if ! ipfs cat /ipns/k51qzi5uqu5diql7mejg4dfn35igqqf22202vgv3sepjrsobtya2xihqqtshbe > ipns.json; then
+            cid=$(ipfs name resolve k51qzi5uqu5diql7mejg4dfn35igqqf22202vgv3sepjrsobtya2xihqqtshbe)
+            if [ "$cid" == "" ]; then
+              echo "failed to resolve IPNS name...retrying..."
+              sleep 5
+              continue
+            fi
+            if ! ipfs cat $cid > ipns.json; then
               echo "failed to get ipns.json...retrying..."
               sleep 5
               continue
